import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        clay: {
          50: "#fdf8f0",
          100: "#f8ecd8",
          200: "#f0dab0",
          300: "#e6c088",
          400: "#dcaa72",
          500: "#d4a66d",
          600: "#b98b58",
          700: "#9a6e43",
          800: "#7c5836",
          900: "#5e4229",
          950: "#3d2b1a",
        },
        sand: {
          50: "#f4f1e9",
          100: "#ebe7dc",
          200: "#d8d3c6",
          300: "#c5c0b3",
          400: "#bdb8aa",
          500: "#a39d8c",
          600: "#857e6c",
          700: "#6b6558",
          800: "#504b41",
          900: "#38352e",
          950: "#211f1a",
        },
        campo: {
          50: "#eef2ec",
          100: "#dbe4d4",
          200: "#b9cbac",
          300: "#8fac7e",
          400: "#5f7d52",
          500: "#3a5c3a",
          600: "#2c4938",
          700: "#244335",
          800: "#1e3427",
          900: "#182a1f",
          950: "#13251b",
        },
      },
      fontFamily: {
        serif: ["var(--font-heading)"],
        sans: ["var(--font-body)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
